//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimDetail
    {
        public long Id { get; set; }
        public Nullable<long> ClaimId { get; set; }
        public string CPTHCPC { get; set; }
        public Nullable<decimal> AllowedAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    }
}
