//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimEntity
{
    using ClaimModel;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AlgoZyEntities : DbContext
    {
        public AlgoZyEntities()
            : base("name=AlgoZyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Claim> Claims { get; set; }
        public DbSet<ClaimCommentHistory> ClaimCommentHistories { get; set; }
        public DbSet<ClaimDetail> ClaimDetails { get; set; }
        public DbSet<ClaimStatu> ClaimStatus { get; set; }
        public DbSet<ClaimWorkflow> ClaimWorkflows { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<ClaimlistModel> ClaimlistModel { get; set; }
        public virtual ObjectResult<GetClaimlist_Result> GetClaimlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClaimlist_Result>("GetClaimlist");
        }
    }
}
