//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimWorkflow
    {
        public long Id { get; set; }
        public Nullable<long> ClaimId { get; set; }
        public Nullable<long> AssignerId { get; set; }
        public Nullable<long> AssigneeId { get; set; }
        public Nullable<int> ClaimStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
