//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public long Id { get; set; }
        public string PatientName { get; set; }
        public string ProviderName { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<decimal> AllowedAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> ClaimStatusId { get; set; }
        public string LastComment { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string ClaimNo { get; set; }
    }
}
